### ISSUE TITLE
Don't get it to work

### ISSUE THREAD

**Issue by SomeGuyInBelgium** [lynxcs/homebridge-ct200#12]
I'm getting this error:

(node:28985) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at extractJSON (/usr/local/lib/node_modules/homebridge-ct200/index.js:56:20)
    at /usr/local/lib/node_modules/homebridge-ct200/index.js:300:21
(node:28985) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 98)
[18/11/2021, 23:12:07] [Termostaat onder] Encountered error during GET: /system/awayMode/enabled
[18/11/2021, 23:12:07] [Termostaat onder] SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-ct200/node_modules/bosch-xmpp/lib/base-client.js:224:30
    at tryCatcher (/usr/local/lib/node_modules/homebridge-ct200/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-ct200/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-ct200/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-ct200/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-ct200/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/usr/local/lib/node_modules/homebridge-ct200/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/usr/local/lib/node_modules/homebridge-ct200/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/local/lib/node_modules/homebridge-ct200/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/homebridge-ct200/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:464:21)
(node:28985) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at extractJSON (/usr/local/lib/node_modules/homebridge-ct200/index.js:56:20)
    at /usr/local/lib/node_modules/homebridge-ct200/index.js:318:21

this is my config:

        {
            "accessory": "ct200",
            "name": "Termostaat onder",
            "access": "XW5cSPgktxZu6VF6",
            "serial": "101112043",
            "password": "",
            "zone": 1
        },

Thx for your time

**Comment by lynxcs** [comment]
Hmm, sadly this error doesn't say much, could you try running
`bosch-xmpp easycontrol --serial="SERIAL" --access-key="ACCESS" --password="PASSWORD" get /zones/list` and posting the result.

You might not have this command available, in which case you can install it with `sudo npm install -g bosch-xmpp`

**Comment by lynxcs** [comment]
New version has different config format, closing.
