### ISSUE TITLE
[CT200] SyntaxError encountered while sending request! Double-check login details!

### ISSUE THREAD

**Issue by andrewbarnes666** [lynxcs/homebridge-ct200#27]
**Describe Your Problem:**
I upgraded to latest version of homebride-ct200 and I now get the following error:

`[CT200] SyntaxError encountered while sending request! Double-check login details!`

I've verified my password, and have even changed it - in alignment with thinstallation instructions

**Logs:**
First Occurence

```
[3/1/2022, 5:50:38 PM] [CT200] SyntaxError encountered while sending request! Double-check login details!
...
[3/2/2022, 2:38:07 PM] [CT200] SyntaxError encountered while sending request! Double-check login details!
```

These events correspond with the following in home bridge-out.log
```
/2/2022, 2:38:07 PM] [CT200] Updating zone status
```

**Plugin Config:**

```json
        {
            "access": "aaa",
            "serial": "bbb",
            "password": "ccc",
            "away": true,
            "zoneInterval": 2,
            "auxInterval": 5,
            "zones": [
                {
                    "index": 1,
                    "name": "Front Hallway"
                },
                {
                    "index": 2,
                    "name": "Kitchen"
                },
                {
                    "index": 3,
                    "name": "First Bedroom"
                },
                {
                    "index": 4,
                    "name": "Living Room"
                },
                {
                    "index": 5,
                    "name": "Second Bedroom"
                },
                {
                    "index": 6,
                    "name": "Master Bedroom"
                },
                {
                    "index": 8,
                    "name": "Office"
                },
                {
                    "index": 9,
                    "name": "Spare Room"
                }
            ],
            "platform": "CT200"
        },
```

**Screenshots:**
When viewing Thermostat in Apple Home, looks like following ... 
![image](https://user-images.githubusercontent.com/1479888/156385420-d5e9ce17-ea35-455b-9577-c2ac4c02ba3a.png)

**Environment:**

* **Plugin Version**: 2.2.5
* **Homebridge Version**: 1.4.0
* **Node.js Version**: 16.13.0
* **NPM Version**: 8.3.2
* **Operating System**: FreeBSD  12.2-RELEASE-p12 - running as an socage jail

**Comment by lynxcs** [comment]
Hi, sorry for late reply.

If you are still encountering this issue, please try running this command: `bosch-xmpp easycontrol --serial="SERIAL" --access-key="ACCESS" --password="PASSWORD" get /zones/list`
If this command successfully returns a list of zones, then we can be sure that it's not because of bad login details.

Also, does this error happen as soon as you start homebridge, or only after some time?

EDIT: v2.2.6 has been released, which updated the version of bosch-xmpp that the plugin uses. While it's unlikely that it will fix the issue, I'd still recommend updating.

**Comment by andrewbarnes666** [comment]
So that has quietened the noise.  I now get a message:

```
[3/7/2022, 3:39:54 PM] [CT200] Error: MAX_RETRIES_REACHED
    at /usr/local/lib/node_modules/homebridge-ct200/node_modules/bosch-xmpp/lib/base-client.js:181:51
    at tryCatcher (/usr/local/lib/node_modules/homebridge-ct200/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-ct200/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-ct200/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-ct200/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-ct200/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/usr/local/lib/node_modules/homebridge-ct200/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/usr/local/lib/node_modules/homebridge-ct200/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/local/lib/node_modules/homebridge-ct200/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/homebridge-ct200/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (node:internal/timers:464:21)
```

Do you know what the service URL is for the API call?  I can try tracing that connection attempt

**Comment by andrewbarnes666** [comment]
When I run the command from your earlier note (bosch-xmpp), the command times out - no response

```
[user@homebridge ~]$ time bosch-xmpp easycontrol --serial="xxx" --access-key="yyy" --password="zzz" get /zones/list
Error: MAX_RETRIES_REACHED
    at /usr/local/lib/node_modules/bosch-xmpp/lib/base-client.js:181:51
    at tryCatcher (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (node:internal/timers:464:21)

real    1m26.370s
user    0m0.607s
sys     0m0.068s
```

Which ... aligns with the error above in the homebridge logs

**Comment by lynxcs** [comment]
Hmm, curious. What version of CT200 firmware do you have? 03.10?

**Comment by Barclay2k** [comment]
Yes 3.10 is the latest revision.

**Comment by andrewbarnes666** [comment]
Yes, v3.10


--
Andrew Barnes
᚛ᚐᚅᚇᚏᚓᚃ ᚁᚐᚏᚅᚓᚄ᚜

Email:  ***@***.***
Mobile: +353 86 3803633

**Comment by lynxcs** [comment]
> Do you know what the service URL is for the API call? I can try tracing that connection attempt

I believe since v3.6.2 the URL is `xmpp.rrcng.ticx.boschtt.net`

After doing some digging, according to the author of bosch-xmpp
> MAX_RETRIES_REACHED typically points to the Bosch device not having an internet connection (it gets thrown if the code hasn't gotten a response for a request within 2 seconds, for 15 consecutive times).

You can read about it more in-depth [here](https://github.com/robertklep/bosch-xmpp/issues/22)

**Comment by andrewbarnes666** [comment]
Oh interesting - thank you, I'll try restarting it to see if that helps

**Comment by andrewbarnes666** [comment]
Now I get a different error when running bosch-xmpp manually (btw, I've changed the password, same error)

`SyntaxError: Unexpected token � in JSON at position 0
    at JSON.parse (<anonymous>)
    at /usr/local/lib/node_modules/bosch-xmpp/lib/base-client.js:224:30
    at tryCatcher (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/bosch-xmpp/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (node:internal/timers:464:21)`

home bridge-error.log shows
`[3/8/2022, 11:01:18 AM] [CT200] SyntaxError encountered while sending request! Double-check login details!
`

**Comment by andrewbarnes666** [comment]
Here's an interesting one ... I have another jail that has an older version of bosch-xmpp

v1.3.0 works fine
v1.4.0 throws the error listed above

**Comment by andrewbarnes666** [comment]
Interesting - so I reduced the password length to 8 characters, and now it works fine with v1.4.0 of Bosch-xmpp

I've updated the password in homebridge config, and now ct200 is working perfectly

**Comment by andrewbarnes666** [comment]
I've x-ref'd this as an issue [here](https://github.com/robertklep/bosch-xmpp/issues/32)

**Comment by andrewbarnes666** [comment]
@lynxcs FYI - bosch-xmpp has been bumped in response to my issue report ... [here](https://github.com/robertklep/bosch-xmpp/commit/0fe6b5fc293848b6e20bc845de04c0f4b02615fd)

**Comment by lynxcs** [comment]
Nice find. I'll change the bosch-xmpp version used and publish an update.

**Comment by lynxcs** [comment]
I'm going to close this issue now, since it seems to have been resolved.
