### ISSUE TITLE
[CT200] Error: MAX_RETRIES_REACHED

### ISSUE THREAD

**Issue by derjonny88** [lynxcs/homebridge-ct200#33]
Unfortunately, I am currently getting a lot of error messages from the CT200 Homebridge plugin. 

Here is my setup:

Raspberry Pi 3
with Homebridge 1.6 / Node.JS 18.15

CT200:
Firmware: 04.00.00

I constantly get the following error messages in the log:

`[07/04/2023, 03:52:01] [CT200] Error: MAX_RETRIES_REACHED
    at /var/lib/homebridge/node_modules/homebridge-ct200/node_modules/bosch-xmpp/lib/base-client.js:181:51
    at tryCatcher (/var/lib/homebridge/node_modules/homebridge-ct200/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/lib/homebridge/node_modules/homebridge-ct200/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/var/lib/homebridge/node_modules/homebridge-ct200/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/var/lib/homebridge/node_modules/homebridge-ct200/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/var/lib/homebridge/node_modules/homebridge-ct200/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/var/lib/homebridge/node_modules/homebridge-ct200/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/var/lib/homebridge/node_modules/homebridge-ct200/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/var/lib/homebridge/node_modules/homebridge-ct200/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/var/lib/homebridge/node_modules/homebridge-ct200/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (node:internal/timers:476:21)`

**Comment by derjonny88** [comment]
`[4/18/2023, 9:13:55 PM] [CT200] Error: INVALID_RESPONSE
    at /homebridge/node_modules/homebridge-ct200/node_modules/bosch-xmpp/lib/base-client.js:257:23
    at tryCatcher (/homebridge/node_modules/homebridge-ct200/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/homebridge/node_modules/homebridge-ct200/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/homebridge/node_modules/homebridge-ct200/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/homebridge/node_modules/homebridge-ct200/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/homebridge/node_modules/homebridge-ct200/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/homebridge/node_modules/homebridge-ct200/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/homebridge/node_modules/homebridge-ct200/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/homebridge/node_modules/homebridge-ct200/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/homebridge/node_modules/homebridge-ct200/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (node:internal/timers:476:21)
[4/18/2023, 9:13:55 PM] TypeError: Cannot read properties of undefined (reading 'status')
    at /homebridge/node_modules/homebridge-ct200/src/switch.ts:43:25`

**Comment by derjonny88** [comment]
This happen since updating to new Homekit Architecture

**Comment by zivanek** [comment]
I also have same situation. Something strange with bosch servers, beacuse, mobile app every one week I must change token key. Do you have some new update in future ? But plugin is very usefull and I hope to will work in it.

**Comment by zivanek** [comment]
Dear do you have some update for this problems ?
