### ISSUE TITLE
Issue  - No plugin was found for the platform "CT200" in your config.json

### ISSUE THREAD

**Issue by eronnes** [lynxcs/homebridge-ct200#34]
**Describe Your Problem:**
No plugin was found for the platform "CT200" in your config.json, but there is an entry in the config.json?

**Logs:**
5-8-2023 12:22:22] ---
[5-8-2023 12:22:22] ====================
[5-8-2023 12:22:22] ERROR LOADING PLUGIN homebridge-ct200:
[5-8-2023 12:22:22] Error: Cannot find module 'reconnect-core'
Require stack:
- /var/lib/homebridge/node_modules/homebridge-ct200/node_modules/node-xmpp-core/lib/Connection.js
- /var/lib/homebridge/node_modules/homebridge-ct200/node_modules/node-xmpp-core/index.js
- /var/lib/homebridge/node_modules/homebridge-ct200/node_modules/node-xmpp-client/lib/session.js
- /var/lib/homebridge/node_modules/homebridge-ct200/node_modules/node-xmpp-client/lib/Client.js
- /var/lib/homebridge/node_modules/homebridge-ct200/node_modules/node-xmpp-client/index.js
- /var/lib/homebridge/node_modules/homebridge-ct200/node_modules/bosch-xmpp/lib/base-client.js
- /var/lib/homebridge/node_modules/homebridge-ct200/node_modules/bosch-xmpp/index.js
- /var/lib/homebridge/node_modules/homebridge-ct200/dist/client.js
- /var/lib/homebridge/node_modules/homebridge-ct200/dist/thermostat.js
- /var/lib/homebridge/node_modules/homebridge-ct200/dist/platform.js
- /var/lib/homebridge/node_modules/homebridge-ct200/dist/index.js
- /var/lib/homebridge/node_modules/homebridge/lib/plugin.js
- /var/lib/homebridge/node_modules/homebridge/lib/pluginManager.js
- /var/lib/homebridge/node_modules/homebridge/lib/server.js
- /var/lib/homebridge/node_modules/homebridge/lib/cli.js
- /var/lib/homebridge/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Function.Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/var/lib/homebridge/node_modules/homebridge-ct200/node_modules/node-xmpp-core/lib/Connection.js:7:17)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/var/lib/homebridge/node_modules/homebridge-ct200/node_modules/node-xmpp-core/index.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
[5-8-2023 12:22:22] ====================

**Plugin Config:**

 {
            "access": "xxxxxxxxxxW",
            "serial": "xxxxxxxxxx",
            "password": "xxxxxxxxxxxxxxx",
            "away": true,
            "zoneInterval": 2,
            "auxInterval": 5,
            "zones": [
                {
                    "index": 1,
                    "name": "Thermostat"
                }
            ],
            "platform": "CT200",
            "_bridge": {
                "username": "xxxxxxxxxxxxxxx",
                "port": 55675
            }
        },

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by eronnes** [comment]
Is it correct that the access key disappeared in het EasyControl app?
